import type { Metadata } from "next"
import "../styles/globals.css"
import { robotoFont } from "~/lib/get-font"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${robotoFont.className} antialiased`}>{children}</body>
    </html>
  )
}
